name: CI and CD
on:
  push:
    branches:
      - main
jobs:
  ci:
    uses: Lucky3028/turn-on-air-conditioner/.github/workflows/ci.yaml@main
  cd:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          secrets: |
            SWITCHBOT_TOKEN
            SWITCHBOT_CLIENT_SECRET
        env:
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
          SWITCHBOT_CLIENT_SECRET: ${{ secrets.SWITCHBOT_CLIENT_SECRET }}
