name: CI
on:
  pull_request:
  workflow_call:
jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
      - name: Test
        run: npm run test
